Repository codesquad-members-2023/be-java-cafe, pull requests merged in 2023-03, with the labels that each got.

#17 [GOMUNGNAM] 주간 학습 계획 및 3월 14일 일일 학습 계획
  .gitignore
  README.md
Labels: study plan

#18 [이린] step-1 : 1단계 구현 / 회원가입, 명단 정보 조회, 프로필 조회, html 중복코드 제거
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/CafeController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/dto/UserJoinRequestDto.java
  src/main/java/kr/codesqaud/cafe/dto/UserListResponseDto.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/java/kr/codesqaud/cafe/service/UserServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/static/css/index.css
  src/main/resources/static/css/post/form.css
  src/main/resources/static/css/post/show.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/css/user/form.css
  src/main/resources/static/css/user/list.css
  src/main/resources/static/css/user/login.css
  src/main/resources/static/css/user/login_success.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/images/KakaoCI.png
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layout/nav.html
  src/main/resources/templates/post/form.html
  src/main/resources/templates/post/show.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/login_success.html
  src/main/resources/templates/user/profile.html
  src/test/java/kr/codesqaud/cafe/service/UserServiceTest.java
Labels: step-1

#21 [로이] Step-1 구현
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/resources/static/user/list.html
  src/main/resources/static/user/profile.html
Labels: step-1

#22 [Birdie] Step-1 회원 가입 및 목록 조회 기능
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/repository/MemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryMemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/SignUpService.java
  src/main/java/kr/codesqaud/cafe/repository/SignUpServiceImpl.java
  src/main/java/kr/codesqaud/cafe/user/User.java
  src/main/resources/static/index.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/fragment/footer.html
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/fragment/nav.html
  src/main/resources/templates/users/list.html
  src/main/resources/templates/users/profile.html
  src/test/java/kr/codesqaud/cafe/domain/repository/UserSaveTest.java
Labels: step-1

#23 [poro] step-1 회원 가입, 목록, 프로필 조회 구현 및 단위 테스트 작성, html 중복 제거
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/AutoAppConfig.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/JoinService.java
  src/main/java/kr/codesqaud/cafe/domain/JoinServiceImpl.java
  src/main/java/kr/codesqaud/cafe/domain/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/domain/UserRepository.java
  src/main/java/kr/codesqaud/cafe/user/User.java
  src/main/resources/application.properties
  src/main/resources/static/qna/form.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layout/nav.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/kr/codesqaud/cafe/domain/JoinServiceTest.java
  src/test/java/kr/codesqaud/cafe/domain/UserRepositoryTest.java
Labels: step-1

#24 [ManJu] step-1 구현: 회원 가입, 모든 회원조회, 프로필 조회, html 중복코드 제거
  .gitignore
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layout/nav.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
Labels: step-1

#28 [Cire] Step-1 구현 : 회원 가입, 모든 회원조회, 프로필 조회, html 중복코드 제거
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/basic/User.java
  src/main/java/kr/codesqaud/cafe/config/ViewController.java
  src/main/java/kr/codesqaud/cafe/controller/UserLogicController.java
  src/main/java/kr/codesqaud/cafe/repository/UserMemoryRepository.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/footer.html
  src/main/resources/templates/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/navigation_bar.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/kr/codesqaud/cafe/repository/UserMemoryRepositoryTest.java
Labels: step-1

#27 [이린] step-2 : 글작성, 리스트보기, 상세 글 보기
  README.md
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/CafeController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/list.html
Labels: step-2

#31 [Dewey] step-1 구현
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/UserForm.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/static/css/index.css
  src/main/resources/static/css/post/form.css
  src/main/resources/static/css/post/show.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/css/user/form.css
  src/main/resources/static/css/user/list.css
  src/main/resources/static/css/user/login.css
  src/main/resources/static/css/user/login_success.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/images/KakaoCI.png
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layout/nav.html
  src/main/resources/templates/post/form.html
  src/main/resources/templates/post/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/login_success.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/profile_failed.html
  src/test/java/kr/codesqaud/cafe/CafeApplicationTests.java
Labels: step-1

#33 [Birdie] Step - 2
  src/main/java/kr/codesqaud/cafe/article/Article.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleService.java
  src/main/java/kr/codesqaud/cafe/repository/MemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryMemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/SignUpService.java
  src/main/java/kr/codesqaud/cafe/repository/SignUpServiceImpl.java
  src/main/java/kr/codesqaud/cafe/user/User.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/templates/fragment/nav.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/users/error_page.html
  src/main/resources/templates/users/list.html
  src/main/resources/templates/users/update_user.html
  src/main/resources/templates/welcome/index.html
  src/test/java/kr/codesqaud/cafe/domain/repository/ArticleSaveTest.java
  src/test/java/kr/codesqaud/cafe/domain/repository/UserSaveTest.java
Labels: step-2

#34 [Cire] step-2 게시글 작성, 목록 조회, 상세 조회 및 회원 정보 수정 기능 구현
  README.md
  src/main/java/kr/codesqaud/cafe/basic/Article.java
  src/main/java/kr/codesqaud/cafe/basic/User.java
  src/main/java/kr/codesqaud/cafe/config/ViewController.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/UserLogicController.java
  src/main/java/kr/codesqaud/cafe/controller/WelcomeController.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/resources/application.properties
  src/main/resources/templates/fail-something.html
  src/main/resources/templates/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/navigation_bar.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/list.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login-failed.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/kr/codesqaud/cafe/repository/UserMemoryRepositoryTest.java
Labels: step-2

#35 [poro] step-2 글쓰기, 글 목록 조회, 글 상세보기, 회원정보 수정 기능 구현
  README.md
  src/main/java/kr/codesqaud/cafe/AutoAppConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/domain/JoinService.java
  src/main/java/kr/codesqaud/cafe/domain/JoinServiceImpl.java
  src/main/java/kr/codesqaud/cafe/domain/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/domain/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/domain/QnaService.java
  src/main/java/kr/codesqaud/cafe/domain/QnaServiceImpl.java
  src/main/java/kr/codesqaud/cafe/domain/UserRepository.java
  src/main/java/kr/codesqaud/cafe/user/Article.java
  src/main/java/kr/codesqaud/cafe/user/User.java
  src/main/resources/application.properties
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/kr/codesqaud/cafe/domain/ArticleRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/domain/JoinServiceTest.java
  src/test/java/kr/codesqaud/cafe/domain/QnaServiceTest.java
  src/test/java/kr/codesqaud/cafe/domain/UserRepositoryTest.java
Labels: step-2

#38 [core] step-1 구현
  .DS_Store
  README.md
  build.gradle
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/kr/codesqaud/cafe/CafeConfig.java
  src/main/java/kr/codesqaud/cafe/config/MyConfig.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Member.java
  src/main/java/kr/codesqaud/cafe/repository/MemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryMemberRepository.java
  src/main/java/kr/codesqaud/cafe/service/MemberService.java
  src/main/resources/.DS_Store
  src/main/resources/application.properties
  src/main/resources/static/.DS_Store
  src/main/resources/static/css/index.css
  src/main/resources/static/css/post/form.css
  src/main/resources/static/css/post/show.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/css/user/form.css
  src/main/resources/static/css/user/list.css
  src/main/resources/static/css/user/login.css
  src/main/resources/static/css/user/login_success.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/fonts/glyphicons-halflings-regular.eot
  src/main/resources/static/fonts/glyphicons-halflings-regular.svg
  src/main/resources/static/fonts/glyphicons-halflings-regular.ttf
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff2
  src/main/resources/static/images/.DS_Store
  src/main/resources/static/images/80-text.png
  src/main/resources/static/images/KakaoCI.png
  src/main/resources/static/index.html
  src/main/resources/static/js/bootstrap.min.js
  src/main/resources/static/js/jquery-2.2.0.min.js
  src/main/resources/static/js/scripts.js
  src/main/resources/static/post/form.html
  src/main/resources/static/post/show.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/form.html
  src/main/resources/templates/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/list.html
  src/main/resources/templates/login.html
  src/main/resources/templates/login_success.html
  src/main/resources/templates/profile.html
  src/test/java/kr/codesqaud/cafe/service/MemberServiceTest.java
Labels: step-1

#39 [ManJu] step-2 구현: 글쓰기, 글 목록 조회, 게시글 상세보기, 회원정보 수정 기능 구현
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/nav.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/qna/show_failed.html
  src/main/resources/templates/user/form_failed.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile_failed.html
  src/main/resources/templates/user/updateForm.html
Labels: step-2

#36 [Luke] Step1 - 구현
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/main/resources/templates/favicon.ico
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/users/form.html
  src/main/resources/templates/users/list.html
  src/main/resources/templates/users/login.html
  src/main/resources/templates/users/login_failed.html
  src/main/resources/templates/users/profile.html
Labels: step-1

#42 [GOMUNGNAM] step-1 구현
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/WelcomeController.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/domain/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/main/resources/templates/fragment.html
  src/main/resources/templates/index.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
Labels: step-1

#41 [nino] step-2 글 쓰기, 글 목록 조회하기, 게시글 상세보기 구현,회원정보 수정하기
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/web/WebRestController.java
  src/main/resources/application.properties
  src/main/resources/static/qna/form.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/top.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/kr/codesqaud/cafe/repository/UserRepositoryTest.java
Labels: step-2

#46 [Hyun] step-3 구현 : DB연동 및 AWS를 사용해 배포
  .gitignore
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/H2DBArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/H2DBUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/static/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/kr/codesqaud/cafe/repository/H2DBArticleRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/repository/H2DBUserRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/repository/MemoryUserRepositoryTest.java
  src/test/resources/application.properties
  src/test/resources/test-schema.sql
Labels: step-3

#49 [버디][Step3] DB 연결
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  h2/test.mv.db
  h2/test.trace.db
  src/main/java/kr/codesqaud/cafe/article/Article.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleService.java
  src/main/java/kr/codesqaud/cafe/repository/SignUpService.java
  src/main/java/kr/codesqaud/cafe/repository/article/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/H2JDBCArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/member/H2JDBCMemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/member/MemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/member/MemoryMemberRepository.java
  src/main/resources/application.properties
  src/main/resources/static/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/welcome/index.html
  src/test/java/kr/codesqaud/cafe/domain/repository/ArticleSaveTest.java
  src/test/java/kr/codesqaud/cafe/domain/repository/UserSaveTest.java
  src/test/java/kr/codesqaud/cafe/repository/ArticleSaveTest.java
  src/test/java/kr/codesqaud/cafe/repository/UserSaveTest.java
Labels: step-3

#51 [GOMUNGNAM] step-2 글 쓰기 + 회원 정보 수정 기능 구현
  .editorconfig
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/WelcomeController.java
  src/main/java/kr/codesqaud/cafe/domain/article/Article.java
  src/main/java/kr/codesqaud/cafe/domain/article/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/domain/user/User.java
  src/main/java/kr/codesqaud/cafe/domain/user/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/updateForm.html
Labels: step-2

#52 [nino] step-3 구현
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/MemberController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/Member.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/Member/JdbcMemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/Member/MemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/JdbcArticleRepository.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/show.html
  src/test/java/kr/codesqaud/cafe/repository/UserRepositoryTest.java
Labels: step-3

#53 [Dewey] step-2 구현 : 글쓰기 구현, 회원정보 수정 구현
  README.md
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleForm.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/UserForm.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/static/css/index.css
  src/main/resources/static/css/post/form.css
  src/main/resources/static/css/post/show.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/css/user/form.css
  src/main/resources/static/css/user/list.css
  src/main/resources/static/css/user/login.css
  src/main/resources/static/css/user/login_success.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/images/KakaoCI.png
  src/main/resources/static/index.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layout/nav.html
  src/main/resources/templates/post/form.html
  src/main/resources/templates/post/show.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/profile_failed.html
  src/main/resources/templates/user/updateForm.html
Labels: step-2

#56 [poro] step-3 구현 : DB 연결 및 AWS EC2 배포
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/AutoAppConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/Handler.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/model/Article.java
  src/main/java/kr/codesqaud/cafe/model/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/JoinService.java
  src/main/java/kr/codesqaud/cafe/service/QnaService.java
  src/main/java/kr/codesqaud/cafe/service/impl/JoinServiceImpl.java
  src/main/java/kr/codesqaud/cafe/service/impl/QnaServiceImpl.java
  src/main/queries
  src/main/resources/application.properties
  src/main/resources/templates/index.html
  src/test/java/kr/codesqaud/cafe/domain/ArticleRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/domain/JoinServiceTest.java
  src/test/java/kr/codesqaud/cafe/domain/QnaServiceTest.java
  src/test/java/kr/codesqaud/cafe/domain/UserRepositoryTest.java
  system.properties
  test.mv.db
Labels: step-3

#57 [core] step-2 구현
  .gitignore
  src/main/java/kr/codesqaud/cafe/CafeApplication.java
  src/main/java/kr/codesqaud/cafe/CafeConfig.java
  src/main/java/kr/codesqaud/cafe/config/CafeConfig.java
  src/main/java/kr/codesqaud/cafe/config/MyConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryMemberRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/MemberService.java
  src/main/resources/application.properties
  src/main/resources/static/css/qna/bootstrap.min.css
  src/main/resources/static/css/qna/styles.css
  src/main/resources/static/css/user/bootstrap.min.css
  src/main/resources/static/post/form.html
  src/main/resources/static/post/show.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/header.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_success.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/kr/codesqaud/cafe/service/ArticleServiceTest.java
  src/test/java/kr/codesqaud/cafe/service/MemberServiceTest.java
Labels: step-2

#45 [Cire] Step-3 DB를 활용한 저장소 기능 구현, 배포 완료 및 학습계획서 작성
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/basic/Article.java
  src/main/java/kr/codesqaud/cafe/basic/User.java
  src/main/java/kr/codesqaud/cafe/config/repositoryConfig/ConnectionConfig.java
  src/main/java/kr/codesqaud/cafe/config/viewConfig/ViewConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/h2Repository/H2ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/h2Repository/H2UserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/memoryRepository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/memoryRepository/MemoryUserRepository.java
  src/main/resources/application.properties
  src/main/resources/templates/user/updateForm.html
  src/test/java/kr/codesqaud/cafe/repository/UserMemoryRepositoryTest.java
Labels: step-3, study plan

#58 [ManJu] step-3 구현: DB 연결 & AWS EC2 배포
  .gitignore
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/CafeApplication.java
  src/main/java/kr/codesqaud/cafe/SpringConfig.java
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcTemplateArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcTemplateUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/sql/data.sql
  src/main/resources/sql/schema.sql
  src/main/resources/templates/index.html
  src/main/resources/templates/user/list.html
Labels: step-3

#59 [Luke] 3주차 학습 계획
  README.md
Labels: study plan

#60 [nino] 학습계획서 작성
  README.md
Labels: study plan

#61 [Birdie] Step-4 로그인 구현
  README.md
  h2/birdie.mv.db
  src/main/java/kr/codesqaud/cafe/config/MVCConfig.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/repository/member/H2JDBCMemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/member/MemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/member/MemoryMemberRepository.java
  src/main/resources/application-aws.properties
  src/main/resources/application.properties
  src/main/resources/static/qna/form.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/fragment/nav.html
  src/main/resources/templates/qna/qna_form.html
  src/main/resources/templates/users/error_page.html
  src/main/resources/templates/users/form.html
  src/main/resources/templates/users/login.html
  src/main/resources/templates/users/update_user.html
  src/test/java/kr/codesqaud/cafe/repository/UserSaveTest.java
Labels: step-4

#64 [이린] step-4 : 로그인-로그아웃 기능 구현 / 회원정보 업데이트 기능 수정
  .gitignore
  README.md
  autobuild.sh
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/GlobalExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/controller/MemberController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/Member.java
  src/main/java/kr/codesqaud/cafe/exception/LoginFailException.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcMemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemberRepository.java
  src/main/resources/application.properties
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/nav.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
Labels: step-4

#67 [Dewey] step3 구현 : DB 연결 및 AWS EC2 배포
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/dto/ArticleForm.java
  src/main/java/kr/codesqaud/cafe/dto/UserForm.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/show.html
Labels: step-3

#68 [로이] step-4 구현
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/config/JdbcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/repository/UserDao.java
  src/main/java/kr/codesqaud/cafe/repository/UserDto.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/qna/form.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/templates/index.html
  src/main/resources/templates/updateForm.html
  src/test/java/kr/codesqaud/cafe/controller/ArticleControllerTest.java
  src/test/java/kr/codesqaud/cafe/controller/UserControllerTest.java
Labels: step-4

#69 [Cire] Step-4 구현 : 로그인 및 로그아웃 기능 추가
  build.gradle
  src/main/java/kr/codesqaud/cafe/basic/Article.java
  src/main/java/kr/codesqaud/cafe/config/viewConfig/ViewConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/WelcomeController.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/h2Repository/H2ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/h2Repository/H2UserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/memoryRepository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/templates/navigation_bar.html
  src/main/resources/templates/qna/list.html
  src/main/resources/templates/user/createForm.html
  src/main/resources/templates/user/loginForm.html
  src/test/java/kr/codesqaud/cafe/repository/UserMemoryRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/repository/h2Repository/H2ArticleRepositoryTest.java
Labels: step-4

#70 [ManJu] Step04 구현: 추가기능(개인정보 수정 기능) 구현
  src/main/java/kr/codesqaud/cafe/config/SpringConfig.java
  src/main/java/kr/codesqaud/cafe/controller/LoginController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/repository/SessionConst.java
  src/main/resources/templates/layout/nav.html
  src/main/resources/templates/user/error.html
  src/main/resources/templates/user/list.html
Labels: step-4

#71 [GOMUNGNAM] step-3 구현 (DB연동, 배포)
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/MemberController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/article/Article.java
  src/main/java/kr/codesqaud/cafe/domain/article/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/domain/article/NamedJdbcTemplateArticleRepository.java
  src/main/java/kr/codesqaud/cafe/domain/user/Member.java
  src/main/java/kr/codesqaud/cafe/domain/user/MemberRepository.java
  src/main/java/kr/codesqaud/cafe/domain/user/NamedJdbcTemplateMemberRepository.java
  src/main/java/kr/codesqaud/cafe/domain/user/UserRepository.java
  src/main/java/kr/codesqaud/connection/ConnectionConst.java
  src/main/java/kr/codesqaud/connection/DBConnectionUtility.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/main/resources/static/qna/show.html
  src/main/resources/templates/fragment.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/list.html
  src/test/java/kr/codesqaud/cafe/connection/DBConnectionUtilityTest.java
  src/test/java/kr/codesqaud/cafe/domain/user/MemberRepositoryTest.java
Labels: step-3

#73 [감자] step3 배포,피드백 반영
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/cafeservice/controller/AddMemberController.java
  src/main/java/kr/codesqaud/cafe/cafeservice/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/cafeservice/controller/LoginController.java
  src/main/java/kr/codesqaud/cafe/cafeservice/controller/MemberController.java
  src/main/java/kr/codesqaud/cafe/cafeservice/controller/MyAdvice.java
  src/main/java/kr/codesqaud/cafe/cafeservice/domain/Article.java
  src/main/java/kr/codesqaud/cafe/cafeservice/domain/Member.java
  src/main/java/kr/codesqaud/cafe/cafeservice/domain/login/LoginForm.java
  src/main/java/kr/codesqaud/cafe/cafeservice/domain/login/LoginService.java
  src/main/java/kr/codesqaud/cafe/cafeservice/exception/ArticleNotFoundException.java
  src/main/java/kr/codesqaud/cafe/cafeservice/exception/MemberNotFoundException.java
  src/main/java/kr/codesqaud/cafe/cafeservice/repository/H2JdbcTemplateMemberRepository.java
  src/main/java/kr/codesqaud/cafe/cafeservice/repository/MemberRepository.java
  src/main/java/kr/codesqaud/cafe/cafeservice/repository/MemoryMemberRepository.java
  src/main/java/kr/codesqaud/cafe/cafeservice/repository/article/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/cafeservice/repository/article/H2ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/cafeservice/repository/article/H2JdbcTemplateArticleRepository.java
  src/main/java/kr/codesqaud/cafe/cafeservice/repository/article/MemoryArticleRepository.java
  src/main/resources/application.properties
  src/main/resources/sql/data.sql
  src/main/resources/sql/schema.sql
  src/main/resources/templates/css/index.css
  src/main/resources/templates/css/post/form.css
  src/main/resources/templates/css/post/show.css
  src/main/resources/templates/css/reset.css
  src/main/resources/templates/css/user/form.css
  src/main/resources/templates/css/user/list.css
  src/main/resources/templates/css/user/login.css
  src/main/resources/templates/css/user/login_success.css
  src/main/resources/templates/fail.html
  src/main/resources/templates/images/KakaoCI.png
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/error.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_success.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/kr/codesqaud/cafe/cafeservice/domain/login/LoginServiceTest.java
  src/test/java/kr/codesqaud/cafe/cafeservice/repository/H2JdbcTemplateMemberRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/cafeservice/repository/JdbcRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/cafeservice/repository/article/MemoryArticleRepositoryTest.java
Labels: step-3

#77 [Cire] Step-4 : 사용자 관련 예외 처리 기능 추가
  src/main/java/kr/codesqaud/cafe/basic/Article.java
  src/main/java/kr/codesqaud/cafe/basic/User.java
  src/main/java/kr/codesqaud/cafe/config/ConstConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ExceptionController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/exception/userException/UserException.java
  src/main/java/kr/codesqaud/cafe/exception/userException/UserLoginException.java
  src/main/java/kr/codesqaud/cafe/exception/userException/UserSessionExpireException.java
  src/main/java/kr/codesqaud/cafe/exception/userException/UserUpdateException.java
  src/main/java/kr/codesqaud/cafe/repository/h2Repository/H2UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/main/resources/templates/errorPage.html
  src/main/resources/templates/navigation_bar.html
  src/main/resources/templates/qna/list.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/loginForm.html
  src/main/resources/templates/user/updateForm.html
Labels: step-4

#76 [Luke] step-3 구현
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/QnaController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/Qna.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/QnaRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/DBArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/users/DBUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/users/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/users/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/templates/qna/list.html
  src/main/resources/templates/qna/show.html
Labels: step-3

#78 [이린] Refactor : 리뷰 내용 반영, DB 쿼리 추가, 예외처리 리팩토링
  README.md
  dbInit.sql
  src/main/java/kr/codesqaud/cafe/controller/GlobalExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/controller/MemberController.java
  src/main/java/kr/codesqaud/cafe/domain/Member.java
  src/main/java/kr/codesqaud/cafe/exception/ExceptionStatus.java
  src/main/java/kr/codesqaud/cafe/exception/LoginFailException.java
  src/main/java/kr/codesqaud/cafe/exception/ManageMemberException.java
  src/main/java/kr/codesqaud/cafe/repository/H2ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/H2MemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemberRepository.java
  src/main/resources/templates/error.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/updateForm.html
Labels: step-4

#80 [core] step-3 (H2 DB 연결하기 & AWS로 배포하기)
  build.gradle
  src/main/java/kr/codesqaud/cafe/config/CafeConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/Member.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcTemplateArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcTemplateMemberRepository.java
  src/main/resources/application.properties
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/schema.sql
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_success.html
  src/main/resources/templates/user/profile.html
Labels: step-3

#82 [nino] step-5 구현
  README.md
  build.sh
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/LoginController.java
  src/main/java/kr/codesqaud/cafe/controller/MemberController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/exception/ExceptionController.java
  src/main/java/kr/codesqaud/cafe/interceptor/LoginCheckInterceptor.java
  src/main/java/kr/codesqaud/cafe/repository/Member/JdbcMemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/JdbcArticleRepository.java
  src/main/resources/schema.sql
  src/main/resources/static/css/error.css
  src/main/resources/templates/error/401.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/modifiedForm.html
  src/main/resources/templates/qna/show.html
Labels: step-5

#87 [Birdie] Refactor - step 5
  README.md
  src/main/java/kr/codesqaud/cafe/config/WebMvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/ExceptionController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/dto/article/ArticleFormDTO.java
  src/main/java/kr/codesqaud/cafe/dto/article/ArticleUpdateDTO.java
  src/main/java/kr/codesqaud/cafe/dto/user/UserLoginDTO.java
  src/main/java/kr/codesqaud/cafe/exception/AddressException.java
  src/main/java/kr/codesqaud/cafe/interceptor/AddressInterceptor.java
  src/main/java/kr/codesqaud/cafe/interceptor/CacheInvalidInterceptor.java
  src/main/java/kr/codesqaud/cafe/interceptor/LoginInterceptor.java
  src/main/java/kr/codesqaud/cafe/interceptor/UpdateUserInterceptor.java
  src/main/java/kr/codesqaud/cafe/repository/article/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/H2JDBCArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/validation/article/ArticleNewFormValidator.java
  src/main/java/kr/codesqaud/cafe/validation/article/ArticleUpdateValidator.java
  src/main/java/kr/codesqaud/cafe/validation/user/UserJoinValidator.java
  src/main/java/kr/codesqaud/cafe/validation/user/UserLoginValidator.java
  src/main/java/kr/codesqaud/cafe/validation/user/UserUpdateValidator.java
  src/main/resources/data.sql
  src/main/resources/messages.properties
  src/main/resources/schema.sql
  src/main/resources/templates/error/error.html
  src/main/resources/templates/fragment/nav.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/qna/update_article.html
  src/main/resources/templates/welcome/index.html
  src/test/java/kr/codesqaud/cafe/repository/ArticleSaveTest.java
  src/test/java/kr/codesqaud/cafe/repository/ArticleTest.java
  src/test/java/kr/codesqaud/cafe/repository/UserTest.java
  src/test/java/kr/codesqaud/cafe/validation/article/ArticleErrorConstant.java
  src/test/java/kr/codesqaud/cafe/validation/article/ArticleInformationConstant.java
  src/test/java/kr/codesqaud/cafe/validation/article/ArticleUpdateTest.java
  src/test/java/kr/codesqaud/cafe/validation/article/ArticleWriteTest.java
  src/test/java/kr/codesqaud/cafe/validation/user/UserJoinValidateTest.java
  src/test/java/kr/codesqaud/cafe/validation/user/UserLoginValidateTest.java
  src/test/java/kr/codesqaud/cafe/validation/user/UserTestErrorConstant.java
  src/test/java/kr/codesqaud/cafe/validation/user/UserTestInformationConstant.java
  src/test/java/kr/codesqaud/cafe/validation/user/UserUpdateValidateTest.java
Labels: step-5

#83 [이린] Refactor : 단위테스트 추가
  README.md
  autobuild.sh
  dbInit.sql
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/GlobalExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/controller/MemberController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/Member.java
  src/main/java/kr/codesqaud/cafe/dto/SessionUser.java
  src/main/java/kr/codesqaud/cafe/exception/ExceptionStatus.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/H2ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/H2MemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemberRepository.java
  src/main/resources/application.properties
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/nav.html
  src/main/resources/templates/qna/show.html
  src/test/java/kr/codesqaud/cafe/repository/H2ArticleRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/repository/H2MemberRepositoryTest.java
  src/test/resources/application.properties
  src/test/resources/db/init.sql
  src/test/resources/db/initData.sql
Labels: step-4

#88 [Luke] 4주차 학습 계획
  README.md
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/repository/article/DBArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/users/DBUserRepository.java
  src/main/resources/templates/qna/list.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/users/login.html
Labels: study plan

#89 [로이] step-5 구현
  README.md
  src/main/java/kr/codesqaud/cafe/config/JdbcConfig.java
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/ExceptionController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/interceptor/AuthInterceptor.java
  src/main/java/kr/codesqaud/cafe/model/Article.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleDao.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleDto.java
  src/main/java/kr/codesqaud/cafe/repository/UserDao.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/main/resources/static/fonts/glyphicons-halflings-regular.svg
  src/main/resources/static/qna/form.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/error/error.html
  src/main/resources/templates/footer.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/updateForm.html
  src/main/resources/templates/summery/footer.html
  src/main/resources/templates/summery/header.html
  src/main/resources/templates/summery/nav.html
  src/main/resources/templates/summery/subNav.html
  src/main/resources/templates/updateForm.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/show.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/kr/codesqaud/cafe/controller/ArticleControllerTest.java
  src/test/java/kr/codesqaud/cafe/controller/UserControllerTest.java
Labels: step-5

#92 [nino] 학습계획서 작성
  README.md
Labels: study plan

#99 [ManJu] Step06 구현: 댓글 작성 및 삭제, 추가기능 구현(게시글 삭제 & 삭제->삭제상태)
  README.md
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/config/SpringConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/ReplyControl.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Reply.java
  src/main/java/kr/codesqaud/cafe/interceptor/LoginCheckInterceptor.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcTemplateArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcTemplateReplyRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcTemplateUserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/ReplyService.java
  src/main/java/kr/codesqaud/cafe/service/SessionUtil.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/sql/data.sql
  src/main/resources/sql/schema.sql
  src/main/resources/templates/error.html
  src/main/resources/templates/error_delete.html
  src/main/resources/templates/layout/nav.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form_failed.html
Labels: study plan, step-6

#100 [로이] step-6 구현
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/ControllerAdvice.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/model/Reply.java
  src/main/java/kr/codesqaud/cafe/repository/ReplyDao.java
  src/main/java/kr/codesqaud/cafe/repository/ReplyDto.java
  src/main/java/kr/codesqaud/cafe/service/ReplyService.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/main/resources/templates/user/show.html
  src/main/resources/templates/user/updateShow.html
Labels: step-6

#101 [Birdie] Step-6 댓글 기능 추가
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/GlobalExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/controller/ReplyController.java
  src/main/java/kr/codesqaud/cafe/domain/Reply.java
  src/main/java/kr/codesqaud/cafe/interceptor/UpdateUserInterceptor.java
  src/main/java/kr/codesqaud/cafe/repository/article/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/H2JDBCArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/reply/H2JDBCReplyRepository.java
  src/main/java/kr/codesqaud/cafe/repository/reply/ReplyRepository.java
  src/main/java/kr/codesqaud/cafe/util/SessionUtil.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/main/resources/templates/qna/qna_form.html
  src/main/resources/templates/qna/show.html
  src/test/java/kr/codesqaud/cafe/repository/ArticleTest.java
Labels: step-6

#106 [ManJu] Step06 : 요구사항 적용
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/HomeController.java
  src/main/java/kr/codesqaud/cafe/controller/LoginController.java
  src/main/java/kr/codesqaud/cafe/controller/ReplyControl.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcTemplateArticleRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/ReplyService.java
  src/main/java/kr/codesqaud/cafe/service/SessionUtil.java
  src/main/resources/application.properties
  src/main/resources/sql/data.sql
  src/main/resources/sql/schema.sql
  src/main/resources/static/css/styles.css
  src/main/resources/static/fonts/glyphicons-halflings-regular.svg
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/error.html
  src/main/resources/templates/error_delete.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/qna/updateForm.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/updateForm_failed.html
Labels: step-6

#107 [nino] step-6 구현 (추가요구사항x)
  README.md
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/LoginController.java
  src/main/java/kr/codesqaud/cafe/controller/MemberController.java
  src/main/java/kr/codesqaud/cafe/controller/MemberSessionUser.java
  src/main/java/kr/codesqaud/cafe/controller/ReplyController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/Reply.java
  src/main/java/kr/codesqaud/cafe/exception/ExceptionController.java
  src/main/java/kr/codesqaud/cafe/exception/GlobalExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/interceptor/LoginCheckInterceptor.java
  src/main/java/kr/codesqaud/cafe/repository/Member/JdbcMemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/Member/MemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/JdbcArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/reply/JdbcReplyRepository.java
  src/main/java/kr/codesqaud/cafe/repository/reply/ReplyRepository.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/main/resources/templates/error/400.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/405.html
  src/main/resources/templates/error/500.html
  src/main/resources/templates/qna/show.html
  src/test/java/kr/codesqaud/cafe/repository/UserRepositoryTest.java
Labels: step-6

#109 [이린] Step5 : 글 작성자만 글 수정/삭제 가능 기능
  README.md
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/MemberController.java
  src/main/java/kr/codesqaud/cafe/exception/ExceptionStatus.java
  src/main/java/kr/codesqaud/cafe/interceptor/AuthorityInterceptor.java
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/qna/updateForm.html
  src/test/java/kr/codesqaud/cafe/repository/H2ArticleRepositoryTest.java
Labels: step-5

#111 [Luke] step-4 구현
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/article/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/users/DBUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/users/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/users/UserRepository.java
  src/main/java/kr/codesqaud/cafe/util/SessionConst.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/users/edit.html
  src/main/resources/templates/users/list.html
  src/main/resources/templates/users/login_failed.html
Labels: step-4

#113 [Luke] step5 - 구현
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/repository/article/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/DBArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/users/DBUserRepository.java
  src/main/java/kr/codesqaud/cafe/util/ValidateConst.java
  src/main/resources/templates/qna/edit.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/users/list.html
  src/main/resources/templates/util/error.html
Labels: step-5

#112 [Dewey] step5 : 로그인 권한 기능 구현, 게시글 본인만 수정 및 삭제 기능 구현
  README.md
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/UserSession.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/filter/PermissionFilter.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/qna/updateForm.html
  src/main/resources/templates/user/form.html
Labels: step-5
